server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fares-Rbd/ticket-sales-config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: master # Branch to fetch configurations from
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
